v4l2_camera_node:
  ros__parameters:
    
    pixel_format: "YUYV"         
    output_encoding: "rgb8"     
    image_size: [1920, 1080]  
    brightness: 0                
    contrast: 50                 
    saturation: 64               
    hue: 0                       
    white_balance_automatic: 1   
    gamma: 300                   
    gain: 64                     
    power_line_frequency: 2      
    sharpness: 50                
    backlight_compensation: 0    
    auto_exposure: 3                                  
    exposure_time_absolute: 166  
